apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: avrodefs.schemaregistry.def
spec:
  group: schemaregistry.def
  names:
    kind: Avrodef
    plural: avrodefs
    singular: avrodef
    shortNames:
      - sravro
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                schemaContent:
                  type: string
                subjectName:
                  type: string
                schemaType:
                  type: string
                compatibilityType:
                  type: string
                schemaReference:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
